[default_session]
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "l"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "Code îº§ "
path = "~/code"
startup_command = "l"

[[session]]
name = "Dotfiles ó°˜“"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "My binaries"
path = "~/dotfiles/.local/bin"

[[session]]
name = "Kitty config î˜•"
path = "~/.config/kitty"
startup_command = "nvim kitty.conf"

[[session]]
name = "Tmux config î˜•"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "Neovim config î˜•"
path = "~/.config/nvim"

[[session]]
name = "Sesh config î˜•"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
